#!/usr/bin/env bash
#Displaying Best School 10 times using a while loop

count=1

while [ $count -le 10 ]
do
	case $count in
        4)
            echo "4"
            echo "bad luck from China"
            ;;
        9)
            echo "9"
            echo "bad luck from Japan"
            ;;
        17)
            echo "17"
            echo "bad luck from Italy"
            ;;
        *)
            echo $count
            ;;
    esac
    count=$((count+1))
done
