#!/usr/bin/env bash
#Displaying time for 12 hours and 59 minutes

hour=0
minute=1

while [ $hour -lt 12 ] || ([ $hour -eq 12 ] && [ $minute -le 59 ])
do
	printf "%02d:%02d\n" $hour $minute
	minute=$((minute+1))
	if [ $minute -eq 60 ]
	then
        	minute=0
        	hour=$((hour+1))
	fi
done | head -n 70hour=0

